### ISSUE TITLE
Python - Fuzzywuzzy - ImportError: utils

### ISSUE THREAD

**Issue by ruchitinfushion** [ezequielmastrasso/EZLookdevTools#10]
EZLookdevTools/lookdevtools/external/fuzzywuzzy/fuzz.py line 14: cannot import name utils #

**Comment by ezequielmastrasso** [comment]
hi ruchitinfushion, the tools are under heavy development now and not ready for use as mentioned in the README, im actively going through a refactoring now, and getting the the tools ready as soon as i can.

**Comment by ezequielmastrasso** [comment]
Now lookdevtools/python/external is added to the python path, meaning the package import will behave as expected in all scenarios
